name       : f2fs-tools
version    : 1.11.0
release    : 3
source     :
    - https://git.kernel.org/pub/scm/linux/kernel/git/jaegeuk/f2fs-tools.git/snapshot/f2fs-tools-1.11.0.tar.gz : b916ac7cda902502cf18de98da94921f71edbab40fb0437d757f0716191c79e3
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : system.utils
summary    : Userland tools for the f2fs filesystem
description: |
    f2fs-tools are a collection of tools for Flash-Friendly File System (F2FS).
    It allows to format, mount, check and doing other operations on F2FS partitions.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
